# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-tpcc}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ivan R. Judson"]
  s.date = %q{2010-11-05}
  s.description = %q{DataMapper ORM Performance Measurement tool.}
  s.email = %q{irjudson@gmail.com}
  s.executables = ["client", "dm-tpcc"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/dm-tpcc",
     "dm-tpcc.gemspec",
     "lib/dm-tpcc.rb",
     "lib/models/customer.rb",
     "lib/models/district.rb",
     "lib/models/history.rb",
     "lib/models/item.rb",
     "lib/models/new_order.rb",
     "lib/models/order.rb",
     "lib/models/order_line.rb",
     "lib/models/stock.rb",
     "lib/models/warehouse.rb",
     "lib/tpcc/benchmark.rb",
     "lib/tpcc/load.rb",
     "lib/tpcc/setup.rb",
     "lib/tpcc/version.rb",
     "spec/dm-tpcc_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/irjudson/dm-tpcc}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A small set of tools to measure and compare the performance of different data storage systems through the DataMapper ORM.}
  s.test_files = [
    "spec/dm-tpcc_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<data_mapper>, [">= 0"])
      s.add_runtime_dependency(%q<dm-sweatshop>, [">= 0"])
      s.add_runtime_dependency(%q<dm-is-list>, [">= 0"])
      s.add_runtime_dependency(%q<dm-is-versioned>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<dm-postgres-adapter>, [">= 0"])
      s.add_runtime_dependency(%q<dm-mysql-adapter>, [">= 0"])
      s.add_runtime_dependency(%q<dm-persevere-adapter>, [">= 0"])
      s.add_runtime_dependency(%q<dm-sqlite-adapter>, [">= 0"])
      s.add_runtime_dependency(%q<dm-rest-adapter>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<data_mapper>, [">= 0"])
      s.add_dependency(%q<dm-sweatshop>, [">= 0"])
      s.add_dependency(%q<dm-is-list>, [">= 0"])
      s.add_dependency(%q<dm-is-versioned>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<dm-postgres-adapter>, [">= 0"])
      s.add_dependency(%q<dm-mysql-adapter>, [">= 0"])
      s.add_dependency(%q<dm-persevere-adapter>, [">= 0"])
      s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
      s.add_dependency(%q<dm-rest-adapter>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<data_mapper>, [">= 0"])
    s.add_dependency(%q<dm-sweatshop>, [">= 0"])
    s.add_dependency(%q<dm-is-list>, [">= 0"])
    s.add_dependency(%q<dm-is-versioned>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<dm-postgres-adapter>, [">= 0"])
    s.add_dependency(%q<dm-mysql-adapter>, [">= 0"])
    s.add_dependency(%q<dm-persevere-adapter>, [">= 0"])
    s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
    s.add_dependency(%q<dm-rest-adapter>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
  end
end

